### ISSUE TITLE
Discuss: Changing the name query to something different

### ISSUE THREAD

**Issue by rommsen** [dbrattli/Fable.Reaction#11]
For me (thinking in terms of CQS or CQRS) a query is something that is not changing data. It might even be idempotent. But here we are actually performing side requests and explicitely replacing (Elmish) Commands. So when working with Reaction, query always goes against my intuition.

I am not sure about better names but when I showed Elmish.Reaction to my peers I have always talked about streams and never about queries. 

What was the original idea, behind "query" and do you think that we could find a different name for it?

**Comment by dbrattli** [comment]
The word "query" is from [composing queries over asynchronous data sources](https://dl.acm.org/citation.cfm?id=1900173) and is quite a lot used with [rx query](https://www.google.com/search?q=rx+query&ie=utf-8&oe=utf-8&client=firefox-b-ab). The idea is that it's the dual of enumerable, so instead of throwing a (sql) query at some data, you throw the data at a (standing) query. I've probably lived too long together with the "query operators" :)

Stream is definitively possible. I think I did try that name at one point in the beginning, but what do we call the `Program.withQuery` method? 1) `withStream` 2) `withMsgStream` 3) `withMessageStream`, other suggestions?

PS: Even Rx people don't know what a stream is, even if they talk about it all them time. Is it 1) a (composed) observable 2) a subscribed (running) observable. Is it a "hot" observable with an observer at the top aka Rx Subject? However I think it's OK that we use the work `Stream` since we really want to lift us above the core (Rx) Observable level, and it's true that Elmish has a "running" stream of messages.

**Comment by rommsen** [comment]
I was thinking about a different name but I could not find anything beter than stream. Especially because I always use the term when explaining it. 

So I am all positive for `Stream` and `Program.withMsgStream`

I think it is much better than using query

**Comment by dbrattli** [comment]
OK, I`ll do the renaming later today and make a new release.
