### ISSUE TITLE
Autocomplete example not working on Edge browser

### ISSUE THREAD

**Issue by mtnrbq** [dbrattli/Fable.Reaction#12]
Running the example for autocomplete doesn't work for Edge browser.
Specifically, no call is dispatched when typing in the client app pauses, same client accessed from Firefox Dev edition works fine.

Client and server executed using fake build --target run

**Comment by SCullman** [comment]
There are no polyfills defined in the example, so it will just work with modern browsers out of the box.

I didn't clone the autocomplete exmaple, but copied the content of Client.fs into my own setup and it works with Edge.

**Comment by mtnrbq** [comment]
I was using a clone of the repo autocomplete example

**Comment by SCullman** [comment]
I was wrong. It has nothing to do with polyfills. And it worked for me because I already fixed it anf forgot about.
If you test with Chrome, you would get the following error in console log:
![image](https://user-images.githubusercontent.com/5693190/50724600-99339200-10f0-11e9-9c6c-376cb7447db9.png)
It still works in FireFox, but you don't get n error in Edge.
Fix is simple: Change the fetch call from ``http`` to ``https``.
