### ISSUE TITLE
Feliz update breaks Magic example

### ISSUE THREAD

**Issue by fradav** [dbrattli/Fable.Reaction#45]
With the Fable.React update (see my PR) the magic example is broken. 
There was some api changes in Feliz.Bulma (easily fixed) but now the value from server is fetched again and again. Something related to FunctionComponent changes in Fable.React ?

**Comment by dbrattli** [comment]
Perhaps we just need to make a new NuGet of Fable.Reaction.

**Comment by dbrattli** [comment]
Found the bug (I think)

**Comment by fradav** [comment]
Glad to hear it, I was beginning to hit my head on the wall about this.

**Comment by fradav** [comment]
You can use my fork for bulma fixes

**Comment by fradav** [comment]
> Found the bug (I think)

`Array.empty` in `useMemo` ? I don't think so : other examples worked fine... 
It is only in Magic example that the StreamView component is created over and over, until I hit the Ctrl-C in the console : 
![image](https://user-images.githubusercontent.com/701587/82122839-419e3f80-9796-11ea-90b9-21384a16ef1d.png)

**Comment by dbrattli** [comment]
Hmm, it's very strange. If I copy the reaction code into Magic, then it works fine. If I use the NuGet (with the same code) it fails. Go figure ...

**Comment by dbrattli** [comment]
You are right. I think the problem was that the FunctionComponent was defined within a function ([common pitfalls](https://zaid-ajaj.github.io/Feliz/#/Feliz/React/CommonPitfalls)) so for the Magic example things got ugly since it uses 3 components which ended up stepping on each others toes. I have now defined the components at the module level and things seems to work nicely. I btw had to change the signature so that app takes an empty props. Not sure if we should try to change it back to how it was?

```fs
let app () = Reaction.StreamView initialModel view update stream
mountById "reaction-app" (ofFunction app () [])
```

**Comment by dbrattli** [comment]
This seems to work fine:

```fs
let app = Reaction.StreamView initialModel view update stream
mountById "reaction-app" app
```

**Comment by fradav** [comment]
Nice! I confirm it is working with this simpler construct.
Issue closed, thanks you very much!
