### ISSUE TITLE
Dispose subscription when observable terminates

### ISSUE THREAD

**Issue by johannesegger** [dbrattli/Fable.Reaction#47]
Currently a subscription to an observable is only disposed when the subscriber disposes it. If I remember correctly Rx.Net additionally disposes a subscription when the observable terminates (successfully or with an error).

Given the following code:

```fsharp
let o = AsyncRx.take 5 fileChangedObservable // implemented using `FileSystemWatcher`
let! sub = o.SubscribeAsync onFileChanged
```

The resources used for the `FileSystemWatcher` are not released until someone calls `sub.DisposeAsync ()` - even if all of the 5 events have been triggered.

I don't see an easy way to do this because there are so many places where anonymous objects that implement `IAsyncObservable` are created and I don't see an easy way to add the disposal of the subscription to all of them.
In the best case it's not even possible any more to create an `IAsyncObservable` that *doesn't* dispose the subscription on termination.
What do you think?

**Comment by dbrattli** [comment]
Yes, this is what the [`AutoDetachObserver`](https://github.com/dotnet/reactive/blob/master/Rx.NET/Source/src/System.Reactive/Internal/AutoDetachObserver.cs) where doing. We can do the same with `safeObserver` but it's a bit tricky to set the `Disposable` property since it needs to be mutable, i.e 1) create observer 2) subscribe 3) stitch the disposable into the observer so it can dispose when it closes. I'll see what I can do.

**Comment by dbrattli** [comment]
I think this PR should fix the problem: https://github.com/dbrattli/Fable.Reaction/pull/50
